version: '3.8'

services:
  # DB
  db:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    env_file:
      - .env-db
    restart: unless-stopped
    volumes:
      - ./_data/postgres_16:/var/lib/postgresql/data
    stop_grace_period: 5m

  pgadmin:
    image: dpage/pgadmin4:7.8
    env_file:
      - .env-pgadmin
    restart: unless-stopped
    depends_on:
      - db

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stop_grace_period: 1s
    depends_on:
      - db
    env_file:
      - .env-backend
    volumes: 
      - ./_data/log/backend:/var/log/app
    restart: unless-stopped

  # Frontend
  nginx:
    build:
      context: ./frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 80:80