"""123

Revision ID: 721df48f7dbb
Revises: 8dea4e1f6cb8
Create Date: 2023-10-18 08:17:39.796014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "721df48f7dbb"
down_revision: Union[str, None] = "8dea4e1f6cb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
